### ISSUE TITLE
Unknown error height

### ISSUE THREAD

**Issue by self4m** [wiedehopf/readsb#43]
In recent use I have found that some of the ground data received by the aircraft after landing or preparing to take off will be decoded into the air. It is not continuous but intermittent. I am close to the airport, and the surrounding area is relatively open, may I ask whether this is the decoding problem of readsb or the environment

**Comment by wiedehopf** [comment]
This is by far not enough data to give any answer. (not even clear what exactly the issue is)
This command used on a certain aircraft BEFORE the issue happens can help gather data.
viewadsb --show-only <HEX>

There are also some debug flags that you can use in regards to ground / air transition i believe but i haven't used them in a bit so i'd have to look at the code.

There are options to store / replay beast data but it's somewhat complicated to use.

If you're less technical, i'd ask that you expose your beast data via a port somehow so i can take a look.
